apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
bases:
- ../../base

namePrefix: prod-

commonLabels:
  env: prod
  tier: production

replicas:
- name: myapp
  count: 3

images:
- name: myapp
  newTag: dev-latest
