apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Values must be base64 encoded
  # username: echo -n 'admin' | base64  -> YWRtaW4=
  # password: echo -n 'P@ssw0rd123' | base64  -> UEBzc3cwcmQxMjM=
  username: YWRtaW4=
  password: UEBzc3cwcmQxMjM=